var staticData = {
	"DEFAULT_LATITUDE": 14.5980716,
	"DEFAULT_LONGITUDE": 120.9797033,
	"DEFAULT_MAP_ZOOM": 15,
	"DEFAULT_MAP_ZOOM_START": 10,
	"DEFAULT_MAP_ZOOM_END": 25,

	"MAP_INFO_PIN_EXPANDED_WIDTH": "420px",
	"MAP_INFO_PIN_EXPANDED_HEIGHT": "700px",
	"MAP_INFO_PIN_WIDTH": "420px",
	"MAP_INFO_PIN_HEIGHT": "420px",

	"LESS_CATEGORY_LIST_COUNT": 6,
	"REPORT_MAP_PREVIEW_WIDTH": 600,
	"REPORT_MAP_PREVIEW_HEIGHT": 250,

	"MAP_LOCATE_POINTER_ICON": "image/map-locate-pointer.gif",
	"MAP_POINTER_ICON": "image/map-pointer.png",

	"MAP_LOCATE_POINTER_ICON_WIDTH": 32,
	"MAP_LOCATE_POINTER_ICON_HEIGHT": 32,

	"MAP_MARKER_WIDTH": 51,
	"MAP_MARKER_HEIGHT": 64,

	"MAP_POINTER_WIDTH": 41,
	"MAP_POINTER_HEIGHT": 55,

	"REPORT_LIST_PAGE_SIZE": 6,

	"CRIME_LOGO_IMAGE_SOURCE": "image/logotype.png",
	"APP_LOGO_IMAGE_SOURCE": "image/empty.png",

	"DEFAULT_MAP_ADDRESS": "Manila, Philippines",

	"STATIC_SERVER_URL": "http://map.crimewatch.ph",

	"PRODUCTION_FACEBOOK_APPLICATION_ID": "1468622340087258",

	"DEVELOPMENT_FACEBOOK_APPLICATION_ID": "1536844313229530",

	"PRODUCTION_GOOGLE_API_KEY": "AIzaSyBNEu3_Tzbm9cU_1j3ihbJR7vMiFvrMTxs",

	"DEVELOPMENT_GOOGLE_API_KEY": "AIzaSyB8ngCoWixjFPHb6ky4LIlQtrrhVnHy7W4",

	"REPORT_TITLE_MINIMUM_INPUT": 3,
	"REPORT_DESCRIPTION_MINIMUM_INPUT": 25,

	"DEFAULT_PROFILE_IMAGE_SOURCE": "image/profile.png",

	"TWEET_STRING_FORMAT": ""
};

//: @ignore:
if( typeof exports != "undefined" ){
	exports.staticData = staticData;
}
//: @end-ignore