var staticData = {
	"MAP_INFO_PIN_EXPANDED_WIDTH": "480px",
	"MAP_INFO_PIN_EXPANDED_HEIGHT": "720px",
	"MAP_INFO_PIN_WIDTH": "480px",
	"MAP_INFO_PIN_HEIGHT": "420px",
	"LESS_CATEGORY_LIST_COUNT": 6,
	"REPORT_MAP_PREVIEW_WIDTH": 600,
	"REPORT_MAP_PREVIEW_HEIGHT": 250
};